import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Angecia de design digital",
  description: "Generated by create next app",
  viewport: "width=device-width, initial-scale=1",
  icons: {
    icon: "/logo.ico",
    favicon: "/logo.ico",
  },
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  );
}
